language: cpp
dist: bionic
compiler:
  - gcc
  # - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # SFML
  - sudo apt-get install libsfml-dev
  # cppcheck
  - sudo apt-get install -qq cppcheck
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint

services:
 - xvfb

script: 
  - ./download_other_githubs
  # Console
  - qmake -qt=qt5 PicToCodeConsole.pro
  - make debug
   ./PicToCodeConsole
  # Desktop
  - qmake -qt=qt5 PicToCodeDesktop.pro
  - make debug
  - ./PicToCodeDesktop &
  - sudo killall PicToCodeDesktop
  # Get code coverage
  - ./get_code_cov
  - codecov
  # Call OCLint
  - ./do_oclint

after_success:
  - bash <(curl -s https://codecov.io/bash)
